# Generated by Django 4.0.5 on 2022-07-07 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_cart_producttenderrequest_tender_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenderrequest',
            old_name='details',
            new_name='customer_message',
        ),
    ]
