# Generated by Django 4.0.5 on 2022-07-08 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_details_tenderrequest_customer_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'koszyk', 'verbose_name_plural': 'koszyki'},
        ),
        migrations.AlterModelOptions(
            name='profil',
            options={'verbose_name': 'profil', 'verbose_name_plural': 'profile'},
        ),
        migrations.AlterModelOptions(
            name='tenderrequest',
            options={'verbose_name': 'zapytanie', 'verbose_name_plural': 'zapytania'},
        ),
    ]
