# Generated by Django 4.0.5 on 2022-07-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_cart_options_alter_profil_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderrequest',
            name='customer_message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
